# Generated by Django 4.1.7 on 2023-04-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respond',
            new_name='ProjectResponse',
        ),
        migrations.AlterModelTable(
            name='projectresponse',
            table='projectresponse',
        ),
    ]
