# Generated by Django 4.1.7 on 2023-04-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_respond_projectresponse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectResponse',
            new_name='PResponse',
        ),
        migrations.AlterModelTable(
            name='presponse',
            table='presponse',
        ),
    ]
