# Generated by Django 4.1.7 on 2023-04-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_projectresponse_presponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedby', models.CharField(max_length=50)),
                ('quotedamount', models.IntegerField()),
                ('projectid', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'projectresponse',
            },
        ),
    ]
