# Generated by Django 4.1.7 on 2023-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
